// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZFv0cVEnyQAiRce40qSoYEmhfHDTrSaU',
    appId: '1:445431102054:web:ccdbf082dcb760cc7b0ba7',
    messagingSenderId: '445431102054',
    projectId: 'myproject-1-81101',
    authDomain: 'myproject-1-81101.firebaseapp.com',
    storageBucket: 'myproject-1-81101.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgKTCKS7_R6p4scgQ3CzAphClfAtLmbUw',
    appId: '1:445431102054:android:9d0ed49ce6a392627b0ba7',
    messagingSenderId: '445431102054',
    projectId: 'myproject-1-81101',
    storageBucket: 'myproject-1-81101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQkbsRdrsNU1UiNSyIXXrp0v4gb3hyUn0',
    appId: '1:445431102054:ios:527a663cc1521e937b0ba7',
    messagingSenderId: '445431102054',
    projectId: 'myproject-1-81101',
    storageBucket: 'myproject-1-81101.appspot.com',
    iosClientId: '445431102054-ekult8661l8onrhho7ikuokhe9aht1hj.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );
}
